version: '3'
services:
  mongodb:
    image: mongo:4.0.5
    ports:
    - "${MONGODB_EXTERNAL_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
    volumes:
    - ./mongodb-data:/data/db
    - ./backups/db:/var/backups
    restart: ${MONGODB_RESTART}
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
    - "${MONGO_EXPRESS_EXTERNAL_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
    depends_on:
    - mongodb
